### ISSUE TITLE
Create new .ipynb or .py file ?

### ISSUE THREAD

**Issue by Viddesh1** [Viddesh1/RL-Frozen-Lake#1]
Interactive python notebook (.ipynb) file need to be created so that we can test the code. As it provides more flexibility than that of simple python (.py) file.

If there is any need to create a python file we can create it and code can we maintain in the same file.

**Comment by Viddesh1** [comment]
Hi @Ankita01K ,

Could you like to work on this issue?

OR

Should I take care?

Thanks!
Viddesh

**Comment by Viddesh1** [comment]
Adding @shruti-madhav for visibility.

**Comment by Ankita01K** [comment]
Hi @Viddesh1 
I will take care of this task.
@shruti-madhav
